### PR TITLE
add support to set packet data based on EEP description

### PR DESCRIPTION
**Pull request by romor**
A review and comments are highly welcome.
This change is already in use with https://github.com/romor/enocean-mqtt.

### CODE REVIEW

**Comment by kipe** [comment]
At first glance, looks awesome :+1: 
I'll try and do a proper check during the weekend, check against documentation etc. I'll also double check the tests, as it seems there's a couple of (possibly breaking?) API changes. If there are, I'll bump the version number to 0.40.

Can you also provide a link to the room operating panel, if you have one? I'm always interested in find more devices :wink:

**Comment by romor** [comment]
I use the Thermokon SR06 LCD (http://www.thermokon.de/en/products/easysens-transmitters/room-operating-units/sr06-lcd.html).

This might also be interesting: http://micropelt.com/itrv.php

**Comment by kipe** [comment]
Sorry this took so long, I've been extremely busy with work.
However, it all looked great and as I looked into it, there were no API changes and tests were done, so it was an easy merge :smiley: 

I simplified the `Packet` creation a bit in commit c4fcd7c15e4a9f6581fa3488a67bd31ef5e58989, which bases directly on your work.

Thanks for a great commit and links on new devices. Maybe we should start keeping log of devices known to work with this library?

**Comment by romor** [comment]
Thanks for your further enhancements and improvements!

**Pull request merged**
