### PR TITLE
Eep/a5-20-01

### PR DESCRIPTION
**Pull request by douwevandermeij**
Added some missing bits to EEP of A5-20-01

### CODE REVIEW

**Comment by kipe** [comment]
Can you point me to the documation stating the existance of `Self-controlled mode`?

Moreover, the learn-bit is placed in the same location for all 4BS Telegrams and is therefore handled in [here](https://github.com/kipe/enocean/blob/master/enocean/protocol/packet.py#L231) and [here](https://github.com/kipe/enocean/blob/master/enocean/protocol/packet.py#L335).

**Comment by douwevandermeij** [comment]
Good question and good point. About the question, it's not in the EEP
v2.6.2 document, it says not used, but I found it in the documentation of
the MD15-FTL-HE I own.
See
https://www.greenelectric.eu/content/kieback-peter/en/3.09-20.315-01-EN-MD15-FTL-xx-2014-07-30.pdf
page
8, DB_0.BIT_2.
Maybe the MD15-FTL-xx doesn't implement the official protocol?

w: www.karibu-online.nl
m: 06 5060 4033

2017-12-29 19:12 GMT+01:00 Kimmo Huoman <notifications@github.com>:

**Comment by kipe** [comment]
Yup, it's not in 2.6.7 documentation either, therefore I'm a bit hesitant on whether to include this or not... I wonder should this actually be reported to EnOcean Alliance, as the manufacturer is clearly going against the documentation :stuck_out_tongue:

**Comment by douwevandermeij** [comment]
Maybe not merge it indeed, it is/seems too specific for one manufacturer.
Kieback&Peter themselves should contact the EnOcean Alliance to include the bit, it's a handy feature.

**Pull request closed without merging**
