### PR TITLE
Chip version example

### PR DESCRIPTION
**Pull request by alan-martinovic**
A simple example for confirming that the communication with the EnOcean controller is working and decoding the returned data to human readable form

### CODE REVIEW

**Comment by kipe** [comment]
Thanks, I haven't messed around with the controller commands myself, so these examples are very welcome.
One request though, could you change the string formatting to use the utils in `enocean.utils`? This is mainly so that they would get more attention, as they're only used internally at the moment, but can be useful to end-users as well ;)

**Comment by alan-martinovic** [comment]
Will give them a check tomorrow :)

**Comment by kipe** [comment]
Great :+1: 
Not sure if they fit directly, but I assume they should.

**Comment by kipe** [comment]
Sorry for the delay, for some reason Github didn't see notifying of new commits important :confused:

**Pull request merged**
